In [1]:
import numpy as  np

In [2]:
np.__version__

'2.3.5'

In [13]:
arr1 = np.array([1,2,3,4,5, 6])
arr1

array([1, 2, 3, 4, 5, 6])

In [6]:
type(arr1)

numpy.ndarray

In [14]:
arr1.shape

(6,)

In [9]:
arr1.dtype

dtype('int64')

In [15]:
arr1.ndim

1

In [16]:
arr1.size

6

In [17]:
arr2 = np.array([[1,2,3], [4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
arr2.shape

(2, 3)

In [20]:
arr2.size

6

In [21]:
arr2.ndim

2

3D Array

In [25]:
arr3 = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]], [[13,14,15],[16,17,18]]])
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [26]:
arr3.ndim

3

In [27]:
arr3.shape

(3, 2, 3)

In [29]:
arr3.size

18

In [31]:
###Create Random Array

In [32]:
randArr = np.random.rand(3,2,3)
randArr

array([[[0.42712979, 0.61787374, 0.940036  ],
        [0.84798384, 0.53743587, 0.63150693]],

       [[0.86669792, 0.89687083, 0.61285805],
        [0.98114033, 0.55040672, 0.00639565]],

       [[0.19182971, 0.60137004, 0.48525198],
        [0.02582099, 0.8314298 , 0.76452989]]])

In [33]:
randArr.dtype

dtype('float64')

In [35]:
zeros = np.zeros((3,2,3))

In [36]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [37]:
zeros.ndim

3

In [40]:
full = np.full((3,2,3), 18)
full

array([[[18, 18, 18],
        [18, 18, 18]],

       [[18, 18, 18],
        [18, 18, 18]],

       [[18, 18, 18],
        [18, 18, 18]]])

In [42]:
ones = np.ones((3,2,3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [43]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [44]:
arr3[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
int(arr3[0][1][1])

5

In [48]:
arr3[:2]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [49]:
arr3[-1]

array([[13, 14, 15],
       [16, 17, 18]])

###Update and Delete


In [50]:
a1 = np.random.rand(3,2,3)
a2 = np.random.rand(3,2,3)
a1,a2

(array([[[0.10279173, 0.00338112, 0.8391245 ],
         [0.87588292, 0.83839885, 0.42198025]],
 
        [[0.48618599, 0.38741481, 0.56841502],
         [0.78608481, 0.81273967, 0.50075116]],
 
        [[0.50561812, 0.33451588, 0.16525683],
         [0.16337132, 0.52940583, 0.70552463]]]),
 array([[[0.38314991, 0.5367283 , 0.14678893],
         [0.07573316, 0.58172664, 0.00803852]],
 
        [[0.46681767, 0.13236033, 0.32507121],
         [0.7629497 , 0.85171203, 0.74278155]],
 
        [[0.33094225, 0.47525374, 0.31860577],
         [0.16390822, 0.87699406, 0.69659369]]]))

In [51]:
### BAsic Math

In [52]:
np.add(a1,a2)

array([[[0.48594164, 0.54010942, 0.98591343],
        [0.95161609, 1.42012549, 0.43001877]],

       [[0.95300366, 0.51977514, 0.89348623],
        [1.54903451, 1.66445169, 1.24353271]],

       [[0.83656036, 0.80976962, 0.4838626 ],
        [0.32727954, 1.4063999 , 1.40211832]]])

In [54]:
np.subtract(a1,a2)

array([[[-2.80358178e-01, -5.33347179e-01,  6.92335575e-01],
        [ 8.00149760e-01,  2.56672214e-01,  4.13941740e-01]],

       [[ 1.93683189e-02,  2.55054480e-01,  2.43343811e-01],
        [ 2.31351073e-02, -3.89723612e-02, -2.42030388e-01]],

       [[ 1.74675871e-01, -1.40737862e-01, -1.53348942e-01],
        [-5.36897903e-04, -3.47588228e-01,  8.93094055e-03]]])

In [55]:
np.divide(a1,a2)

array([[[2.68280715e-01, 6.29949817e-03, 5.71653811e+00],
        [1.15653813e+01, 1.44122479e+00, 5.24948001e+01]],

       [[1.04149012e+00, 2.92697072e+00, 1.74858617e+00],
        [1.03032324e+00, 9.54242326e-01, 6.74156704e-01]],

       [[1.52781376e+00, 7.03867954e-01, 5.18687495e-01],
        [9.96724399e-01, 6.03659542e-01, 1.01282087e+00]]])

In [56]:
np.multiply(a1,a2)

array([[[0.03938464, 0.00181474, 0.12317419],
        [0.06633339, 0.48771895, 0.00339209]],

       [[0.22696021, 0.05127835, 0.18477536],
        [0.59974317, 0.69222015, 0.37194872]],

       [[0.16733039, 0.15897992, 0.05265178],
        [0.0267779 , 0.46428577, 0.49146401]]])

In [57]:
### statastical Operation

In [58]:
sqrt = np.sqrt(25)
abs = np.abs(-34)
power = np.power(2,3)
log = np.log(25)
min = np.min(a1)
max = np.max(a2)

In [59]:
sqrt

np.float64(5.0)

In [61]:
abs

np.int64(34)

In [62]:
power

np.int64(8)

In [63]:
log

np.float64(3.2188758248682006)

In [64]:
min

np.float64(0.0033811189327024316)

In [65]:
max

np.float64(0.8769940621796715)

In [68]:
### Update

In [69]:
arr3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [70]:
arr3[0][1][1] = 0
arr3

array([[[ 1,  2,  3],
        [ 4,  0,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [73]:
arr3.sort()     
arr3

array([[[ 1,  2,  3],
        [ 0,  4,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [74]:
#Reshape

In [76]:
arr3.shape

(3, 2, 3)

In [79]:
reshape = arr3.reshape((3,3,2))
reshape

array([[[ 1,  2],
        [ 3,  0],
        [ 4,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]]])

In [81]:
reshape = arr3.reshape((2,3,3))
reshape

array([[[ 1,  2,  3],
        [ 0,  4,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [82]:
### Appending And inserting

In [83]:
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [84]:
new = np.ones((3,2,3))

In [85]:
new

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [90]:
append = np.append(zeros, new, axis=1)
append

array([[[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [92]:
append = np.append(zeros, new, axis=0)
append

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [93]:
 append.shape

(6, 2, 3)

In [96]:
inserted = np.insert(zeros, 1, new, axis=0) #(arr1, index, arr2)
inserted

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [100]:
arr4 = np.random.rand(3,2,3)
arr4

array([[[0.12727141, 0.91346558, 0.70226753],
        [0.76201552, 0.20551702, 0.33948496]],

       [[0.64731182, 0.95658445, 0.72914608],
        [0.50878104, 0.59785449, 0.05419679]],

       [[0.56265593, 0.42257418, 0.97034671],
        [0.24842823, 0.13795078, 0.79603599]]])

In [103]:
arr5 = np.delete(arr4, 0, axis=1)
arr5

array([[[0.76201552, 0.20551702, 0.33948496]],

       [[0.50878104, 0.59785449, 0.05419679]],

       [[0.24842823, 0.13795078, 0.79603599]]])

In [104]:
np.save('new_array', arr5)

In [105]:
np.load('new_array.npy')

array([[[0.76201552, 0.20551702, 0.33948496]],

       [[0.50878104, 0.59785449, 0.05419679]],

       [[0.24842823, 0.13795078, 0.79603599]]])